# Generated by Django 5.0.1 on 2024-01-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bigges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='big/')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='big/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('numbers', models.IntegerField()),
                ('massage', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Komputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='komputer/')),
                ('bio', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Koylak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='koylak/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Manfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('image', models.ImageField(upload_to='manfor/')),
            ],
        ),
        migrations.CreateModel(
            name='Small',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='small/')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='watch/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Womanfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='manfor')),
                ('date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
